* Added support to disable/enable GNSS sentences. * If the sanity check fails the script will exit with error code. This error code can be further processed by the calling function.

diff --git a/sensors/check_functionality b/sensors/check_functionality
--- a/sensors/check_functionality
+++ b/sensors/check_functionality
@@ -88,6 +88,7 @@ nOption=0
 sOption=0
 sensValues=
 re='^[0-9]+$'
+sanityCheckFailed=0
 
 help
 
@@ -202,6 +203,7 @@ then
         done
     else
         echo "ERROR: Cannot get CPU temperature"    
+        exit 1
     fi
     
     if [ $sOption == "1" ]
@@ -246,14 +248,17 @@ then
             # convert float to integer
             tempInt=${temp%%.*}
             
-            if ! [[ $tempInt =~ $re ]] ; then
-               echo "ERROR: ${tempInt}"
+            if ! [[ $tempInt =~ $re ]]
+            then
+                echo "ERROR: ${tempInt}"
+                exit 1
             else            
                 # check if temperature is valid
                 if [ $tempInt -gt $temperatureHigh -o $tempInt -lt $temperatureLow ]
                 then
                     echo "ERROR: Temperature out of range. The sensor might not work properly."
-                    sensValues=$(echo "${sensValues}pressureTemp:x;")  
+                    sensValues=$(echo "${sensValues}pressureTemp:x;")
+                    sanityCheckFailed=1  
                 else
                     sensValues=$(echo "${sensValues}pressureTemp:${temp};")
                 fi  
@@ -262,14 +267,17 @@ then
             # convert float to integer
             pressureInt=${pressure%%.*}
                 
-            if ! [[ $pressureInt =~ $re ]] ; then
-               echo "ERROR: ${pressureInt}"
+            if ! [[ $pressureInt =~ $re ]]
+            then
+                echo "ERROR: ${pressureInt}"
+                exit 1
             else     
                 # check if pressure is valid
                 if [ $pressureInt -gt $pressureHigh -o $pressureInt -lt $pressureLow ]
                 then
                     echo "ERROR: Pressure out of range. The sensor might not work properly."
                     sensValues=$(echo "${sensValues}pressure:x;")  
+                    sanityCheckFailed=1
                 else
                     sensValues=$(echo "${sensValues}pressure:${pressure};")
                 fi  
@@ -309,13 +317,16 @@ then
             tempInt=${temp%%.*}
             
             # check if temperature is valid
-            if ! [[ $tempInt =~ $re ]] ; then
-               echo "ERROR: ${tempInt}"
+            if ! [[ $tempInt =~ $re ]]
+            then
+                echo "ERROR: ${tempInt}"
+                exit 1
             else
                 if [ $tempInt -gt $temperatureHigh -o $tempInt -lt $temperatureLow ]
                 then
                     echo "ERROR: Temperature out of range. The sensor might not work properly."
                     sensValues=$(echo "${sensValues}mpuTemp:x;")  
+                    sanityCheckFailed=1
                 else
                     sensValues=$(echo "${sensValues}mpuTemp:${temp};")
                 fi  
@@ -349,5 +360,10 @@ then
     echo ${sensValues} > "${pwd}/${sensorFile}"
     echo "Sensor data written to ${pwd}/${sensorFile}"
 fi   
+
+if [ $sanityCheckFailed -eq 1 ]
+then
+    exit 1
+fi
  
 exit 0
